### PR TITLE
Pads

### PR DESCRIPTION
**Pull request by f3tus**
-Pads have been added for the columns
-Pads can be scrolled with 'j' and 'k' (not perfect, but allows reading past the first couple of posts).
-The background colour is now the default background colour of the terminal. This should probably only be done when colour themes are added, but it enables transparency.
-The terminal can be resized without crashing, but the columns don't resize properly if the size becomes too small.
-The program crashes if the script is started from a small window. This is due to the menu bar being hard coded, but you knew that already.

### CODE REVIEW

**Comment by LumenTeun** [comment]
Cool, you got the pull request up.
It looks promising, but there are a few issues, the most visible one being that changing subreddit doesn't actually show the posts from the new sub.

Also, do you think you could clear up the commits a bit, e.g. remove the parts where you're changing the domain width or adding and then deleting comments? I believe [this link](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) will help with that, specifically the "Squash your changes"-part, but I might be wrong; honestly, I shouldn't even be looking at code right now, let alone trying to comment on it. It's 4 in the morning and I need to sleep.

But yeah, fix the subreddit thing for now. Looking forward to grasping this a bit better in the morning! Night.
Oh, and the color change looks great by the way. :)

**Comment by LumenTeun** [comment]
Sorry that it took a whole day to respond. Unfortunately, studies needs to be priority number 1.

Regarding #12: There's no need to start a new PR for your changes. Every change you make to the branch you asked to merge will be added to the active pull request. It's way easier to keep track of which commits have been added when and in response to what feedback this way.
I'm closing #12 and reopening this one. Keep all discussion in here from now on :)

You seem to have misunderstood the rebasing thing (no worries, it's confusing as fuck at first..)
You need to do an interactive rebase at the merge base commit (which in this case is 04f706d61576491549c809853debcef1bac0cd22), then you'll have to edit the appropriate commits (e.g. removing the change in domainwidth), squash some (e.g. the subreddit fix) and remove some (e.g. the "fixed default domainwidht" one).
Sorry if this is way more confusing than it should be, I'm not feeling very pedagogic today.
If you want to, we could open a chat and I'll walk you through the process? There are a bunch of small, asethetic things with the code I'd like to have changed, but I don't want to "steal" your commit, since you're the one who made the change.

**Comment by f3tus** [comment]
sigh. It seems feb278b has 04f706d a parent now. I think what I did wrong before messed up my stuff. I could just delete this branch and start fresh? It will be easy to add my code. And will look neat without all these random merges and shit I've done :)

**Comment by LumenTeun** [comment]
Hahah I think you're not using the right commit as a base for your rebase. If the rebase is done correctly, all the previous commits will disappear and you'll end up with just the one(s) you want, it looks very neat.
If you want to just get your code merged, you could start a new branch like you said and just add the code, but since there's no hurry to get the code in there (we don't exactly have a huge user base waiting for a fix) you can always take this opportunity to figure out Git and GitHub :)
And, like I said, if you want to, I'm more than willing to help you through it, command by command, in a chat. ;)

**Comment by f3tus** [comment]
Torture! XD. Okay:
git rebase --interactive 04f706d61576491549c809853debcef1bac0cd22
then nano opens (cuz f vim).
When I did the first rebase, there were an entry for every commit. I squashed all (Also the one I should have deleted) except the top one, because that one pointed to your commit. Then I closed nano. It said something like "rebase successful, heads and shit updated". Then I went to github and didn't see any changes. Then I thought "mmm it's local maybe? So push?" so:
git status
"Your branch is behind yadayada, do a merge to fix, do git push"
git push
"some error blabla you should merge!"
i merge, the end...
THEN.
I re-did everything except now it gave issues because I was already pointing to to your commit (like it is now). Hack hack hack. Try again, with:
git rebase --interactive 04f706d61576491549c809853debcef1bac0cd22
all my commits are there again, also the combined commit. This time I remove the one I should have deleted, and squash all but the top one pointing to you. Once I close, they say I have an error with one of them, "please fix, your options are ,continue skip, abort".i say abort. i do the steps again. same error. this time SKIP. another commit has an error, SKIP! "you have rebased"
check github. nothing. same steps, push and merge (because they say so). I've google a bit, and these are pretty much the steps to rebase. It makes sense, and my last commit IS pointing to your commit, so I really have no idea how to remove all the bloat from my history :/

**Comment by f3tus** [comment]
YES! I fixed it. push should have been push --force

**Comment by LumenTeun** [comment]
Firstly: Vim is superior! ;)
Secondly: Congratulations, it looks good! There's some formatting that needs to be done, like adding spaces in some places because it looks better, but I can fix that myself, unless you want to go through this whole ordeal again? Otherwise, I'm ready to merge?

**Comment by f3tus** [comment]
Thanks! Sorry for adding stuff at the last minute, but if the window is very small, the title would basically disappear and only the url and subreddit would be visible. Now its the other way around, so the post can at least be read. I'll remove it if it sucks :)
And for the spaces, I think you should fix them, so I can see how for next time! 
Merge if you're ready. God natt!

**Comment by LumenTeun** [comment]
No problem, I'm liking the changes. :)
Haha, I would say "good day" in your language, but seems like South Africa has 11 official languages...

**Pull request merged**
