### PR TITLE
Pads

### PR DESCRIPTION
**Pull request by f3tus**
Horizontal scrolling, and a fix for resizing bug. I'll try to add a cursor, so we can scroll single lines next time.

### CODE REVIEW

**Comment by f3tus** [comment]
Seems to work now finally.. Need... slee..p... zzzzzzzz

**Comment by LumenTeun** [comment]
Nice, I've been thinking of the highlight feature for quite some time now, just never got around to implementing it. Thanks!
Tip for the future: If you find a bug in your code, close the PR and announce it before you start working on it. Not a big deal with this repo and a non-harmful bug like that, but you don't want to let someone push faulty code into a master branch at some big project ;)

**Comment by f3tus** [comment]
@LumenTeun The subMax and domainMax were supposed to be the lengths of the largest sub length and the largest domain length. The pads were supposed to use those values as a reference to how far those pads should be cropped. For example, if you browse r/pics the domain is usually very small (imgur.com), and that leaves a large white space. Anyway, It was something I was working on, and it didn't work yet, but didn't break anything, so thats why they were there :/. I shouldn't have pushed those changes yet, my bad. And thanks for the tip. Makes sense. Will close PR next time. :)

**Comment by LumenTeun** [comment]
@f3tus Okay, I see :) Try to keep pushed commits as clean and understandable as possible, or explain what's going on and why.

**Comment by f3tus** [comment]
Will do!

**Pull request merged**
